// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      coffee: {
        compile: {
          files: [
            {
              cwd: 'app/',
              expand: true,
              src: "**/*.coffee",
              dest: 'app',
              ext: '.js'
            }, {
              cwd: 'login/',
              expand: true,
              src: "**/*.coffee",
              dest: 'login',
              ext: '.js'
            }, {
              cwd: 'config/',
              expand: true,
              src: "**/*.coffee",
              dest: 'config',
              ext: '.js'
            }, {
              cwd: 'public/coffeescript/',
              expand: true,
              src: "**/*.coffee",
              dest: 'public/javascript',
              ext: '.js'
            }, {
              cwd: 'models/',
              expand: true,
              src: "**/*.coffee",
              dest: 'models',
              ext: '.js'
            }
          ],
          options: {
            sourceMap: false,
            header: true
          }
        }
      },
      watch: {
        coffeesrc: {
          files: ['**/*.coffee'],
          tasks: ['coffee']
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-notify');
    return grunt.registerTask('default', ['coffee', 'watch']);
  };

}).call(this);
