// Generated by CoffeeScript 1.6.3
(function() {
  var express, keys, nib, passport, stylus;

  passport = require("passport");

  express = require("express");

  stylus = require("stylus");

  nib = require("nib");

  keys = require("../config/keys")();

  module.exports = function() {
    var TwitterStrategy, app;
    app = express();
    app.use(express.cookieSession({
      secret: "doyouwannaknowmysecret?"
    }));
    app.set("views", __dirname + "/views");
    app.use(express["static"](__dirname + "/../public"));
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(app.router);
    passport.serializeUser(function(user, done) {
      console.log('passport.serializeUser', user);
      return done(null, user.id);
    });
    passport.deserializeUser(function(id, done) {
      console.log('passport.deserializeUser id: ', id);
      return done(null, id);
    });
    TwitterStrategy = require("passport-twitter").Strategy;
    passport.use(new TwitterStrategy({
      consumerKey: keys.consumer_key,
      consumerSecret: keys.consumer_secret,
      callbackURL: "http://localhost:3000/login/auth/twitter/callback"
    }, function(token, tokenSecret, profile, done) {
      console.log('token: ', token);
      console.log('tokenSecret: ', tokenSecret);
      console.log('profile: ', profile);
      return done(null, profile);
    }));
    app.get("/auth/twitter", passport.authenticate("twitter"));
    app.get("/auth/twitter/callback", passport.authenticate("twitter", {
      successRedirect: "/twitterio",
      failureRedirect: "/login"
    }));
    return app.get('/', function(req, res, next) {
      return res.render("index", {});
    });
  };

}).call(this);
