// Generated by CoffeeScript 1.6.3
(function() {
  var controller, keys, twitter;

  twitter = require("ntwitter");

  keys = require("../../config/keys")();

  controller = {};

  module.exports = function(_app, _socket) {
    var app, changeTrack, socket, track, twit;
    twit = new twitter(keys);
    track = "wimbledon";
    app = _app;
    socket = _socket;
    changeTrack = function(_track, client) {
      return twit.stream("statuses/filter", {
        track: _track
      }, function(stream) {
        stream.on("data", function(data) {
          return client.emit("message", data);
        });
        return stream.on("destroy", function(response) {
          return console.log("Destroying stream...");
        });
      });
    };
    socket.on("connection", function(client) {
      console.log("Connected!");
      changeTrack(track, client);
      return client.on("change_track", function(_track) {
        track = _track.track;
        console.log("Using track(s): ", track);
        return changeTrack(track, client);
      });
    });
    return controller;
  };

  controller.load = function(template, req, res, next) {
    if (!template) {
      return next(new Error("missing template"));
    }
    return res.render(template, {});
  };

  controller.index = function(req, res, next) {
    return res.render("home/index", {});
  };

}).call(this);
