// Generated by CoffeeScript 1.6.3
(function() {
  var ObjectId, Schema, Tweet;

  Schema = require("mongoose").Schema;

  ObjectId = Schema.ObjectId;

  Tweet = module.exports = new Schema({
    user_name: {
      type: String,
      required: true
    },
    profile_image_url: {
      type: String,
      required: true
    },
    text: {
      type: String,
      required: true
    },
    id_str: {
      type: String,
      required: true
    },
    retweeted: {
      type: Boolean,
      "default": false
    },
    created_at: {
      type: Date
    }
  });

  Tweet.statics.getLatestTweets = function(callback) {
    return this.find().sort("_id", "descending").limit(15).find({}, callback);
  };

  Tweet.statics.findByUser = function(user_name, callback) {
    return this.findOne({
      user_name: user_name
    }, callback);
  };

  Tweet.pre("save", function(next) {
    console.log("Saving...");
    return next();
  });

  Tweet.pre("remove", function(next) {
    console.log("removing...");
    return next();
  });

  Tweet.pre("init", function(next) {
    console.log("initializing...");
    return next();
  });

}).call(this);
