// Generated by CoffeeScript 1.6.3
(function() {
  var Schema, mongoose, userSchema;

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  userSchema = new Schema({
    id_str: String,
    screen_name: String,
    token: String,
    tokenSecret: String,
    description: String,
    url: String,
    profile_image_url: String,
    profile_image_url_https: String
  });

  module.exports = mongoose.model("User", userSchema);

}).call(this);
