// Generated by CoffeeScript 1.6.3
(function() {
  var mongoose;

  mongoose = require("mongoose");

  module.exports = function() {
    return mongoose.model("Tweet", require("../app/models/tweet"));
  };

}).call(this);
