// Generated by CoffeeScript 1.6.3
(function() {
  var config, environments, errors, express, hooks, http, models, mongoose, nib, routes, stylus;

  express = require("express");

  mongoose = require("mongoose");

  stylus = require("stylus");

  nib = require("nib");

  models = require("./models");

  config = require("./config");

  routes = require("./routes");

  environments = require("./environments");

  errors = require("./errors");

  hooks = require("./hooks");

  http = require("http");

  module.exports = function() {
    var app, port, server, socket;
    app = express();
    server = http.createServer(app);
    socket = require("socket.io").listen(server);
    config(app);
    environments(app);
    routes(app, socket);
    errors(app);
    hooks(app);
    port = process.env.PORT || 3000;
    server.listen(port);
    console.log("\u001b[36mtwitter-io\u001b[90m v%s\u001b[0m running as \u001b[1m%s\u001b[0m on http://%s:%d", app.set("version"), app.set("env"), app.set("host"), app.get("port"));
    return app;
  };

}).call(this);
