// Generated by CoffeeScript 1.6.3
(function() {
  var express, http;

  express = require("express");

  http = require("http");

  module.exports = function() {
    var app, port, server, socket, twitterio;
    app = express();
    server = http.createServer(app);
    socket = require("socket.io").listen(server);
    twitterio = require("../app")(socket);
    app.use('/twitterio', twitterio);
    port = process.env.PORT || 3000;
    server.listen(port);
    return console.log("\u001b[36mtwitter-io\u001b[90m v%s\u001b[0m running as \u001b[1m%s\u001b[0m on http://%s:%d", app.set("version"), app.set("env"), app.set("host"), app.get("port"));
  };

}).call(this);
