// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app) {
    var port;
    port = process.env.PORT || 3000;
    app.configure("development", function() {
      return this.set("host", "localhost").set("port", port).set("ENV", "development");
    });
    app.configure("production", function() {
      return this.set("port", port).set("ENV", "production");
    });
    return app;
  };

}).call(this);
