// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app) {
    var NotFound;
    NotFound = function(msg) {
      this.name = "NotFound";
      Error.call(this, msg);
      return Error.captureStackTrace(this, arguments_.callee);
    };
    NotFound.prototype.__proto__ = Error.prototype;
    app.use(function(err, req, res) {
      console.log(err);
      res.status(500);
      return res.render('home/500', {
        error: err
      });
    });
    return app;
  };

}).call(this);
