// Generated by CoffeeScript 1.6.3
(function() {
  var ev;

  ev = require("../app/hooks/event");

  module.exports = function(app) {
    return app.on("event:send:tweets", ev.send_tweets);
  };

}).call(this);
