// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(app, socket) {
    var home;
    home = require("../app/controllers/home_controller")(app, socket);
    app.get("/", home.index);
    return app.get("/about", home.load.bind(null, "home/about"));
  };

}).call(this);
